default:
  - active
  - listed
roles:
  anonymous:
    - user:read
  active:
    - task:create
    - user:self:update
    - user:self:destroy
    - role:self:listed:grant
    - role:self:listed:revoke
  listed: []
  admin:
    - '*'