get:
  tags:
    - Tasks
  summary: Retrieve a single task
  description: This endpoint allows authenticated users to retrieve one of the tasks that they own.
  operationId: getTask
  security:
    - bearerAuth: []
  parameters:
    - $ref: "./schemas.yml#/TaskID"
    - $ref: "./schemas.yml#/TaskFields"
  responses:
    200:
      description: The task requested.
      content:
        application/json:
          schema:
            $ref: "./schemas.yml#/TaskResponse"
    401:
      description: Only authenticated users can retrieve tasks.
    403:
      description: Tasks are private; you can't read other users' tasks.
