openapi: 3.0.3
info:
  title: To Do API
  description: |-
    A RESTful API for creating, reading,
    updating, and deleting to-do tasks, but
    really this repository is an example of
    how to use the API Starter.
  termsOfService: https://example.com/terms
  contact:
    email: you@example.com
  license:
    name: GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: '1.0'
servers:
  - url: https://api.example.com/v1/
tags:
  - name: Tasks
    description: Operations related to creating, reading, updating, or deleting tasks.
  - name: Users
    description: Operations related to users and user records.
  - name: Authentication
    description: Authentication
  - name: Accounts
    description: The OAuth 2.0 provider accounts that a user can associate with her account.
paths:
  /accounts:
    $ref: "../collections/accounts/docs/path-collection.yml"
  /accounts/{provider}:
    $ref: "../collections/accounts/docs/path-resource.yml"
  /auth/tokens:
    $ref: "../collections/auth/tokens/docs/path-collection.yml"
  /auth/providers:
    $ref: "../collections/auth/providers/docs/path-collection.yml"
  /tasks:
    $ref: "../collections/tasks/docs/path-collection.yml"
  /tasks/{taskId}:
    $ref: "../collections/tasks/docs/path-resource.yml"
  /users/{userId}:
    $ref: "../collections/users/docs/path-resource.yml"
  /users/{userId}/roles/{role}:
    $ref: "../collections/users/roles/docs/path-resource.yml"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
